@extends('layouts.marketing')

@section('title', 'مستندات API | آویاتو')
@section('body_class', 'bg-[#F5F8FD]')

@section('content')
<div x-data="{ copied: null, copy(value, key) { navigator.clipboard?.writeText(value); this.copied = key; setTimeout(() => this.copied = null, 1600); } }" class="px-4 pb-20 pt-28 md:px-8 lg:px-10">
    <div class="mx-auto max-w-7xl">
        <section class="rounded-[2rem] bg-[#071B3A] px-6 py-12 text-white shadow-xl md:px-12"><p class="text-sm font-black text-blue-300">AVIATO API · V1</p><h1 class="mt-4 max-w-3xl text-4xl font-black leading-tight md:text-6xl">کنترل حساب و کیف پول، با چند درخواست ساده.</h1><p class="mt-6 max-w-2xl text-base leading-8 text-blue-100 md:text-lg">با کلید API حساب خود، موجودی و تراکنش‌های یک فضای کاری را از سرویس خودتان بخوانید. این نسخه فقط دسترسی خواندن دارد؛ شارژ و مدیریت ماشین‌ها در نسخه‌های بعدی اضافه می‌شوند.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('customer.login') }}" class="rounded-xl bg-white px-5 py-3 text-sm font-black text-[#071B3A]">ورود و ساخت کلید</a><a href="#authentication" class="rounded-xl border border-white/20 px-5 py-3 text-sm font-black text-white">شروع سریع</a></div></section>
        <div class="mt-8 grid gap-8 lg:grid-cols-[230px_minmax(0,1fr)]"><aside class="hidden lg:block"><div class="sticky top-28 rounded-2xl border border-slate-200 bg-white p-4 text-sm font-bold"><a href="#authentication" class="block rounded-lg px-3 py-2 text-blue-700">احراز هویت</a><a href="#wallet" class="block rounded-lg px-3 py-2 text-slate-600">موجودی کیف پول</a><a href="#transactions" class="block rounded-lg px-3 py-2 text-slate-600">تراکنش‌ها</a><a href="#errors" class="block rounded-lg px-3 py-2 text-slate-600">خطاها</a></div></aside>
            <main class="space-y-8">
                <section id="authentication" class="rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><p class="text-xs font-black text-blue-600">01 · AUTHENTICATION</p><h2 class="mt-2 text-2xl font-black">احراز هویت</h2><p class="mt-4 leading-8 text-slate-600">از پنل مشتری در بخش پروفایل، یک کلید بسازید. کلید را فقط هنگام ساخت می‌بینید و در همه درخواست‌ها به صورت Bearer Token ارسال می‌کنید.</p><div class="mt-5 rounded-xl bg-slate-950 p-4"><div class="flex items-center justify-between"><span class="text-xs font-bold text-slate-400">Header</span><button @click="copy('Authorization: Bearer YOUR_API_KEY', 'auth')" class="text-xs font-black text-blue-300" x-text="copied === 'auth' ? 'کپی شد' : 'کپی'">کپی</button></div><code class="mt-3 block text-sm text-emerald-300" dir="ltr">Authorization: Bearer YOUR_API_KEY</code></div><p class="mt-4 text-sm leading-7 text-slate-500">آدرس پایه: <code class="rounded bg-slate-100 px-2 py-1 font-mono text-slate-700" dir="ltr">{{ url('/api/v1') }}</code></p></section>
                <section id="wallet" class="rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><p class="text-xs font-black text-blue-600">02 · WALLET</p><div class="mt-2 flex flex-wrap items-center gap-3"><span class="rounded-lg bg-emerald-100 px-3 py-1 font-mono text-xs font-black text-emerald-700" dir="ltr">GET</span><code class="font-mono text-sm text-slate-800" dir="ltr">/projects/{project_uuid}/wallet</code></div><p class="mt-4 leading-8 text-slate-600">موجودی کیف پول فضای کاری را برمی‌گرداند. کلید باید به مشتری‌ای تعلق داشته باشد که در پروژه دسترسی مالی دارد.</p><div class="mt-5 rounded-xl bg-slate-950 p-4"><div class="flex items-center justify-between"><span class="text-xs font-bold text-slate-400">cURL</span><button @click="copy('curl -X GET &quot;{{ url('/api/v1') }}/projects/PROJECT_UUID/wallet&quot; -H &quot;Accept: application/json&quot; -H &quot;Authorization: Bearer YOUR_API_KEY&quot;', 'wallet')" class="text-xs font-black text-blue-300" x-text="copied === 'wallet' ? 'کپی شد' : 'کپی'">کپی</button></div><code class="mt-3 block overflow-x-auto text-xs leading-7 text-emerald-300" dir="ltr">curl -X GET "{{ url('/api/v1') }}/projects/PROJECT_UUID/wallet" -H "Accept: application/json" -H "Authorization: Bearer YOUR_API_KEY"</code></div><pre class="mt-4 overflow-x-auto rounded-xl bg-slate-50 p-4 text-xs leading-7 text-slate-700" dir="ltr"><code>{ "data": { "project_id": "PROJECT_UUID", "balance": 1250000, "currency": "IRR", "display_amount": "125,000 تومان" }, "meta": { "request_id": "REQUEST_ID" } }</code></pre></section>
                <section id="transactions" class="rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><p class="text-xs font-black text-blue-600">03 · TRANSACTIONS</p><div class="mt-2 flex flex-wrap items-center gap-3"><span class="rounded-lg bg-emerald-100 px-3 py-1 font-mono text-xs font-black text-emerald-700" dir="ltr">GET</span><code class="font-mono text-sm text-slate-800" dir="ltr">/projects/{project_uuid}/wallet/transactions</code></div><p class="mt-4 leading-8 text-slate-600">تراکنش‌های قابل مشاهده همان فضای کاری را به صورت صفحه‌بندی‌شده برمی‌گرداند.</p><div class="mt-4 space-y-2 text-sm text-slate-600"><p><code class="font-mono text-slate-800" dir="ltr">type</code> · all, credit, debit, charge, refund, adjustment</p><p><code class="font-mono text-slate-800" dir="ltr">per_page</code> · عددی بین 1 و 100؛ مقدار پیش‌فرض 25</p><p><code class="font-mono text-slate-800" dir="ltr">from / to</code> · تاریخ مانند 2026-07-01</p></div><div class="mt-5 rounded-xl bg-slate-950 p-4"><span class="text-xs font-bold text-slate-400">PHP cURL</span><code class="mt-3 block overflow-x-auto text-xs leading-7 text-emerald-300" dir="ltr">$ch = curl_init('{{ url('/api/v1') }}/projects/PROJECT_UUID/wallet/transactions?per_page=25'); curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); curl_setopt($ch, CURLOPT_HTTPHEADER, ['Accept: application/json', 'Authorization: Bearer YOUR_API_KEY']); $data = json_decode(curl_exec($ch), true); curl_close($ch);</code></div><pre class="mt-4 overflow-x-auto rounded-xl bg-slate-50 p-4 text-xs leading-7 text-slate-700" dir="ltr"><code>{ "data": [{ "id": 42, "type": "credit", "amount": 500000, "balance_before": 750000, "balance_after": 1250000, "currency": "IRR", "created_at": "2026-07-13T08:30:00+03:30" }], "links": { "next": null }, "meta": { "current_page": 1, "last_page": 1 } }</code></pre></section>
                <section id="errors" class="rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><p class="text-xs font-black text-blue-600">04 · ERRORS</p><h2 class="mt-2 text-2xl font-black">پاسخ خطا</h2><p class="mt-4 leading-8 text-slate-600">در خطاها کد HTTP و <code dir="ltr">error.code</code> را بررسی کنید. برای پشتیبانی، Request ID را ارسال کنید.</p><div class="mt-5 grid gap-3 md:grid-cols-2"><pre class="overflow-x-auto rounded-xl bg-red-50 p-4 text-xs leading-7 text-red-900" dir="ltr"><code>401 Unauthorized: { "error": { "code": "Unauthenticated", "message": "Unauthenticated." }, "meta": { "request_id": "REQUEST_ID" } }</code></pre><pre class="overflow-x-auto rounded-xl bg-amber-50 p-4 text-xs leading-7 text-amber-900" dir="ltr"><code>403 Forbidden: { "error": { "code": "project_forbidden", "message": "You do not have billing access to this project." }, "meta": { "request_id": "REQUEST_ID" } }</code></pre></div><div class="mt-3 rounded-xl bg-slate-50 p-4 text-sm leading-7 text-slate-600"><strong class="text-slate-900">422</strong> پارامتر نامعتبر · <strong class="text-slate-900">429</strong> محدودیت درخواست · <strong class="text-slate-900">5xx</strong> خطای موقت سرویس.</div></section>
                <section class="rounded-2xl border border-blue-100 bg-blue-50 p-6 md:p-8"><p class="text-xs font-black text-blue-700">SECURITY</p><h2 class="mt-2 text-2xl font-black">نکات امنیتی</h2><ul class="mt-4 space-y-3 text-sm leading-7 text-blue-950"><li>کلید را داخل Git، لاگ، مرورگر یا کد سمت کاربر قرار ندهید.</li><li>در صورت افشا، از پروفایل آن را لغو و کلید جدید بسازید.</li><li>برای هر سرویس یا محیط، کلید جداگانه بسازید.</li><li>درخواست‌ها با Request ID ثبت می‌شوند و اطلاعات محرمانه ذخیره نمی‌شود.</li></ul></section>
            </main>
        </div>
    </div>
</div>
@endsection
