@extends('layouts.marketing')

@section('title', 'مستندات API | آویاتو')
@section('body_class', 'bg-[#F5F8FD]')

@section('content')
@php($baseUrl = url('/api/v1'))
<div x-data="{ activeSection: 'workflow', mobileNav: false, copied: null, copy(value, key) { navigator.clipboard?.writeText(value); this.copied = key; setTimeout(() => this.copied = null, 1400); } }"
     x-init="const sections = [...$el.querySelectorAll('main section[id]')]; const setActive = () => { const line = window.scrollY + 150; let current = sections[0]?.id; sections.forEach(section => { if (section.offsetTop <= line) current = section.id; }); activeSection = current || 'workflow'; }; window.addEventListener('scroll', setActive, { passive: true }); setActive();"
     class="px-4 pb-24 pt-24 md:px-8 lg:px-10">
    <div class="mx-auto max-w-7xl">
        <header class="rounded-[1.75rem] border border-slate-200 bg-white px-6 py-10 shadow-[0_20px_60px_-35px_rgba(7,27,58,.35)] md:px-10">
            <span class="rounded-full bg-[#EAF2FF] px-3 py-1.5 text-xs font-black text-[#0069FF]">AVIATO API · V1</span>
            <h1 class="mt-5 max-w-4xl text-3xl font-black leading-[1.35] text-slate-950 md:text-5xl">از انتخاب زیرساخت تا حذف امن VM</h1>
            <p class="mt-4 max-w-3xl text-sm leading-8 text-slate-600 md:text-base">با API گزینه‌های معتبر را کشف کنید، ماشین مجازی بسازید، وضعیت آماده‌سازی و اطلاعات اتصال را بخوانید و حذف را با تایید نام انجام دهید.</p>
            <div class="mt-6 flex flex-wrap gap-3"><a href="#workflow" class="rounded-xl bg-[#0069FF] px-4 py-3 text-sm font-black text-white">شروع سریع</a><a href="{{ route('customer.login') }}" class="rounded-xl border border-slate-200 px-4 py-3 text-sm font-black text-slate-700">ساخت کلید API</a></div>
        </header>

        <div class="mt-8 grid gap-8 lg:grid-cols-[15rem_minmax(0,1fr)]">
            <aside class="hidden lg:block"><nav class="sticky top-24 rounded-2xl border border-slate-200 bg-white p-3" aria-label="فهرست مستندات">
                @foreach ([['GUIDE', 'workflow', 'نمای کلی workflow'], ['GUIDE', 'authentication', 'احراز هویت و abilities'], ['DISCOVER', 'options', 'گزینه‌های ساخت VM'], ['DISCOVER', 'projects', 'پروژه و UUID'], ['LIFECYCLE', 'list-vms', 'لیست VMها'], ['LIFECYCLE', 'create-vm', 'ساخت VM'], ['LIFECYCLE', 'get-vm', 'جزئیات VM'], ['LIFECYCLE', 'delete-vm', 'حذف VM'], ['OPERATIONS', 'states', 'وضعیت‌ها و polling'], ['OPERATIONS', 'credentials', 'رمز و SSH'], ['REFERENCE', 'fields', 'فیلدهای درخواست'], ['REFERENCE', 'errors', 'خطاها'], ['REFERENCE', 'security', 'امنیت']] as [$group, $id, $label])
                    @if ($loop->first || $group !== $previousGroup)<p class="px-3 pb-1 pt-3 text-[10px] font-black tracking-[.16em] text-slate-400">{{ $group }}</p>@endif
                    <a href="#{{ $id }}" @click="activeSection = '{{ $id }}'" :class="activeSection === '{{ $id }}' ? 'bg-[#EEF5FF] text-[#0069FF]' : 'text-slate-600'" class="block rounded-lg px-3 py-2 text-sm font-bold hover:bg-slate-50">{{ $label }}</a>
                    @php($previousGroup = $group)
                @endforeach
            </nav></aside>
            <div class="min-w-0 space-y-8">
                <div class="lg:hidden"><button type="button" @click="mobileNav = !mobileNav" class="w-full rounded-xl border border-slate-200 bg-white p-3 text-right text-sm font-black">فهرست مستندات</button><nav x-show="mobileNav" class="mt-2 grid gap-1 rounded-xl border border-slate-200 bg-white p-3">@foreach ([['workflow','نمای کلی workflow'],['authentication','احراز هویت'],['options','گزینه‌ها'],['projects','پروژه‌ها'],['list-vms','لیست VMها'],['create-vm','ساخت VM'],['get-vm','جزئیات VM'],['delete-vm','حذف VM'],['states','وضعیت‌ها'],['credentials','رمز و SSH'],['fields','فیلدها'],['errors','خطاها'],['security','امنیت']] as [$id,$label])<a @click="mobileNav=false; activeSection='{{ $id }}'" href="#{{ $id }}" class="rounded-lg p-2 text-sm font-bold">{{ $label }}</a>@endforeach</nav></div>
                <div class="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-8 text-amber-950"><strong>UUID واقعی پروژه:</strong> مقدار <code dir="ltr">YOUR_PROJECT_UUID</code> را از آدرس یا صفحه جزئیات همان پروژه در پنل مشتری بردارید؛ نام پروژه یا UUID مشتری قابل استفاده نیست.</div>

                <section id="workflow" class="scroll-mt-24 rounded-2xl border border-[#B8D6FF] bg-[#F4F8FF] p-6 md:p-8"><h2 class="text-2xl font-black text-slate-950">Workflow کامل</h2><div class="mt-5 grid gap-3 md:grid-cols-5">@foreach (['کلید با abilities لازم','options را بخوانید','VM را بسازید','detail را poll کنید','با نام دقیق حذف کنید'] as $i => $step)<div class="rounded-xl bg-white p-4 text-sm font-black"><span class="text-[#0069FF]">{{ $i + 1 }}</span><p class="mt-3">{{ $step }}</p></div>@endforeach</div><p class="mt-5 text-sm leading-8 text-slate-600">ساخت و حذف asynchronous هستند. بعد از ساخت، VM با <code dir="ltr">provisioning_status: pending</code> برمی‌گردد و باید endpoint جزئیات را poll کنید.</p></section>
                <section id="authentication" class="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><h2 class="text-2xl font-black text-slate-950">احراز هویت و abilities</h2><p class="mt-4 text-sm leading-8 text-slate-600">در همه درخواست‌ها هدر <code dir="ltr">Authorization: Bearer YOUR_API_KEY</code> و <code dir="ltr">Accept: application/json</code> را بفرستید. کلید را از پروفایل مشتری بسازید.</p><div class="mt-4 grid gap-3 sm:grid-cols-3 text-sm"><div class="rounded-xl bg-slate-50 p-4"><code dir="ltr">vm:read</code><p class="mt-2">options، list و detail</p></div><div class="rounded-xl bg-slate-50 p-4"><code dir="ltr">vm:create</code><p class="mt-2">ساخت VM</p></div><div class="rounded-xl bg-slate-50 p-4"><code dir="ltr">vm:delete</code><p class="mt-2">حذف VM</p></div></div></section>
                <section id="options" class="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><x-api-endpoint method="GET" path="/projects/{project_uuid}/virtual-machines/options" ability="vm:read" /><p class="mt-4 text-sm leading-8 text-slate-600">ابتدا این endpoint را بخوانید. فقط locationهای فعال و غیرتعمیراتی، imageهای فعال، خانواده و نسخه OS، mapping سازگاری، bundleهای فعال، قیمت، ظرفیت IP، wallet و quota را برمی‌گرداند. credential، secret، <code dir="ltr">provider_metadata</code> و script داخلی هرگز برگردانده نمی‌شوند.</p><pre class="mt-4 overflow-x-auto rounded-xl bg-[#071B3A] p-4 text-xs leading-7 text-emerald-300" dir="ltr"><code>curl -X GET "{{ $baseUrl }}/projects/YOUR_PROJECT_UUID/virtual-machines/options" \
  -H "Authorization: Bearer YOUR_API_KEY"</code></pre></section>
                <section id="projects" class="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><h2 class="text-2xl font-black text-slate-950">پروژه و project UUID</h2><p class="mt-4 text-sm leading-8 text-slate-600">هر مسیر VM با <code dir="ltr">/projects/{project_uuid}</code> محدود می‌شود. عضویت پروژه و دسترسی customer portal همزمان بررسی می‌شود؛ VMهای مشتری یا پروژه دیگر قابل مشاهده نیستند.</p></section>
                @foreach ([['list-vms','GET','/projects/{project_uuid}/virtual-machines','vm:read','لیست VMها','پارامترهای اختیاری: search، status و per_page. VMهای deleted به صورت پیش‌فرض حذف می‌شوند.'],['get-vm','GET','/projects/{project_uuid}/virtual-machines/{virtual_machine_uuid}','vm:read','جزئیات VM','رمز عبور در list و detail هرگز برنمی‌گردد. IP، username و SSH command فقط در صورت آماده بودن اتصال ارائه می‌شود.'],['delete-vm','DELETE','/projects/{project_uuid}/virtual-machines/{virtual_machine_uuid}','vm:delete','حذف امن VM','بدنه درخواست باید شامل confirmation برابر display_name دقیق باشد. حذف queue می‌شود و status فورا deleting می‌شود؛ درخواست تکراری idempotent است.']] as [$id,$method,$path,$ability,$title,$description])
                    <section id="{{ $id }}" class="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><x-api-endpoint method="{{ $method }}" path="{{ $path }}" ability="{{ $ability }}" /><h2 class="mt-4 text-xl font-black text-slate-950">{{ $title }}</h2><p class="mt-3 text-sm leading-8 text-slate-600">{{ $description }}</p>@if ($id === 'delete-vm')<pre class="mt-4 overflow-x-auto rounded-xl bg-[#071B3A] p-4 text-xs leading-7 text-emerald-300" dir="ltr"><code>curl -X DELETE "{{ $baseUrl }}/projects/YOUR_PROJECT_UUID/virtual-machines/VM_UUID" \
  -H "Authorization: Bearer YOUR_API_KEY" -H "Content-Type: application/json" \
  -d '{"confirmation":"My Production Server"}'</code></pre>@endif</section>
                @endforeach
                <section id="create-vm" class="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><x-api-endpoint method="POST" path="/projects/{project_uuid}/virtual-machines" ability="vm:create" /><p class="mt-4 text-sm leading-8 text-slate-600"><code dir="ltr">cloud_image_id</code> و location و bundle را فقط از options انتخاب کنید. با bundle، ابعاد از bundle می‌آید؛ بدون bundle، هر سه <code dir="ltr">cpu_cores</code>، <code dir="ltr">ram_gb</code> و <code dir="ltr">disk_gb</code> لازم است. password تولیدشده فقط یک‌بار در <code dir="ltr">generated_login_password</code> پاسخ create می‌آید.</p><pre class="mt-4 overflow-x-auto rounded-xl bg-[#071B3A] p-4 text-xs leading-7 text-emerald-300" dir="ltr"><code>curl -X POST "{{ $baseUrl }}/projects/YOUR_PROJECT_UUID/virtual-machines" \
  -H "Authorization: Bearer YOUR_API_KEY" -H "Content-Type: application/json" \
  -d '{"infrastructure_location_id":12,"cloud_image_id":4,"vm_bundle_id":2,"display_name":"My Production Server","login_username":"ubuntu","ssh_public_key":"ssh-ed25519 ..."}'</code></pre></section>
                <section id="states" class="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><h2 class="text-2xl font-black text-slate-950">وضعیت‌ها و polling</h2><p class="mt-4 text-sm leading-8 text-slate-600"><code dir="ltr">pending</code> یعنی آماده‌سازی در صف است، <code dir="ltr">ready</code> یعنی اتصال آماده، <code dir="ltr">failed</code> یعنی خطای آماده‌سازی، <code dir="ltr">deleting</code> یعنی حذف در صف و <code dir="ltr">deleted</code> یعنی حذف نهایی. پس از create هر چند ثانیه detail را بخوانید؛ پس از delete نیز تا پایان عملیات همین کار را انجام دهید.</p></section>
                <section id="credentials" class="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><h2 class="text-2xl font-black text-slate-950">Credentials و SSH</h2><p class="mt-4 text-sm leading-8 text-slate-600">رمز ورودی تولیدشده فقط در پاسخ create است. آن را ذخیره امن کنید؛ API مسیر بازیابی password ندارد. وقتی <code dir="ltr">ssh_ready</code> برابر true شد، از <code dir="ltr">ssh_command</code> استفاده کنید.</p></section>
                <section id="fields" class="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><h2 class="text-2xl font-black text-slate-950">فیلدهای درخواست</h2><p class="mt-4 text-sm leading-8 text-slate-600">فیلدها: infrastructure_location_id، cloud_image_id، vm_bundle_id، display_name، login_username، login_password، ssh_public_key، requires_invoice و ابعاد cpu_cores/ram_gb/disk_gb در حالت بدون bundle. image/location و image/bundle باید سازگار باشند و quota، wallet و ظرفیت IP نیز بررسی می‌شوند.</p></section>
                <section id="errors" class="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><h2 class="text-2xl font-black text-slate-950">خطاها</h2><p class="mt-4 text-sm leading-8 text-slate-600"><code dir="ltr">401</code> توکن نامعتبر، <code dir="ltr">403</code> ability یا دسترسی پروژه، <code dir="ltr">404</code> VM خارج از scope، <code dir="ltr">409</code> عملیات ناسازگار، <code dir="ltr">422</code> validation، quota، wallet یا compatibility و <code dir="ltr">429</code> محدودیت درخواست است. برای پشتیبانی <code dir="ltr">meta.request_id</code> را ارسال کنید.</p><pre class="mt-4 rounded-xl bg-red-50 p-4 text-xs leading-7 text-red-900" dir="ltr"><code>{ "error": { "code": "validation_error", "fields": {} }, "meta": { "request_id": "REQUEST_ID" } }</code></pre></section>
                <section id="wallet-reference" class="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><h2 class="text-xl font-black text-slate-950">Wallet endpoints</h2><p class="mt-3 text-sm leading-8 text-slate-600">برای سازگاری با API قبلی، endpointهای کیف پول همچنان در دسترس هستند:</p><div class="mt-4 grid gap-2 text-sm font-bold"><span dir="ltr">/projects/{project_uuid}/wallet</span><span dir="ltr">/projects/{project_uuid}/wallet/transactions</span><span dir="ltr">/projects/{project_uuid}/wallet/transactions/{transaction}</span></div><div class="mt-4 flex flex-wrap gap-3 text-xs"><span>Get remaining balance</span><span>List transactions</span><span>Get one transaction</span></div></section>
                <section id="security" class="scroll-mt-24 rounded-2xl border border-blue-100 bg-[#EEF5FF] p-6 md:p-8"><h2 class="text-2xl font-black text-slate-950">نکات امنیتی</h2><p class="mt-4 text-sm leading-8 text-blue-950">کلید را در Git، log یا browser نگذارید؛ برای هر سرویس کلید جدا بسازید و در صورت افشا revoke کنید. قابلیت‌های اضافی را به کلید ندهید و password اولیه را فقط در secret manager ذخیره کنید.</p></section>
            </div>
        </div>
    </div>
</div>
@endsection
