@extends('layouts.admin')
@inject('money', 'App\Services\WalletService')
@section('title', 'ماشین‌های مجازی')
@section('content')
<div class="px-4 py-6 md:px-8 lg:px-10">
@if (session('status'))<div class="mb-5 rounded-lg border border-[#B8D6FF] bg-[#EBF3FF] px-4 py-3 text-sm font-bold text-[#031B4E]">{{ session('status') }}</div>@endif
<div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 class="text-2xl font-black">ماشین‌های مجازی</h1><p class="mt-2 text-sm text-slate-500">اتصال VM به مشتری، Proxmox و محاسبه PAYG.</p></div><a href="{{ route('admin.virtual-machines.create') }}" class="rounded-lg bg-[#0069FF] px-5 py-3 text-sm font-black text-white">VM جدید</a></div>
<form class="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-5"><input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="جستجو نام یا IP" class="rounded-lg border border-slate-200 px-4 py-3"><select name="customer_id" class="rounded-lg border border-slate-200 px-4 py-3"><option value="">همه مشتریان</option>@foreach($customers as $id => $name)<option value="{{ $id }}" @selected((string)($filters['customer_id'] ?? '') === (string)$id)>{{ $name }}</option>@endforeach</select><select name="project_id" class="rounded-lg border border-slate-200 px-4 py-3"><option value="">همه پروژه ها</option>@foreach($projects as $id => $name)<option value="{{ $id }}" @selected((string)($filters['project_id'] ?? '') === (string)$id)>{{ $name }}</option>@endforeach</select><select name="status" class="rounded-lg border border-slate-200 px-4 py-3"><option value="">همه وضعیت‌ها</option><option value="running" @selected(($filters['status'] ?? '') === 'running')>روشن</option><option value="stopped" @selected(($filters['status'] ?? '') === 'stopped')>خاموش</option><option value="suspended" @selected(($filters['status'] ?? '') === 'suspended')>تعلیق</option></select><button class="rounded-lg bg-slate-950 px-5 py-3 text-sm font-black text-white">فیلتر</button></form>
<div class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><table class="min-w-full text-right text-sm"><thead class="bg-slate-50 text-xs font-black text-slate-500"><tr><th class="px-5 py-4">VM</th><th class="px-5 py-4">Project</th><th class="px-5 py-4">Project Owner</th><th class="px-5 py-4">Created By</th><th class="px-5 py-4">Billing Customer</th><th class="px-5 py-4">منابع</th><th class="px-5 py-4">وضعیت</th><th class="px-5 py-4">هزینه ماهانه فعلی</th><th class="px-5 py-4">عملیات</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($vms as $vm)<tr><td class="px-5 py-4"><a href="{{ route('admin.virtual-machines.show', $vm) }}" class="font-black text-slate-950" dir="ltr">{{ $vm->name }}</a><span class="block text-xs text-slate-500" dir="ltr">{{ $vm->ip_address ?: 'no-ip' }} · {{ $vm->proxmoxServer?->name ?: 'local' }}</span></td><td class="px-5 py-4 font-bold">{{ $vm->project?->name ?: '—' }}</td><td class="px-5 py-4">{{ $vm->project?->owner?->name ?: '—' }}</td><td class="px-5 py-4">{{ $vm->creator?->name ?: '—' }}</td><td class="px-5 py-4"><a class="font-bold text-[#0069FF]" href="{{ route('admin.customers.show', $vm->customer) }}">{{ $vm->customer?->name ?: '—' }}</a></td><td class="px-5 py-4">{{ $vm->cpu_cores }} CPU / {{ $vm->ram_gb }}GB / {{ $vm->disk_gb }}GB</td><td class="px-5 py-4"><span class="rounded-md px-2.5 py-1 text-xs font-black {{ $vm->status === 'running' ? 'bg-[#EBF3FF] text-[#0069FF]' : 'bg-slate-100 text-slate-600' }}">{{ $vm->status === 'running' ? 'روشن' : ($vm->status === 'stopped' ? 'خاموش' : 'تعلیق') }}</span></td><td class="px-5 py-4 font-black">{{ $money->format($vm->isRunning() ? $billing->estimateMonthly($vm) : $billing->estimateStoppedMonthly($vm)) }}</td><td class="px-5 py-4"><a class="font-black text-[#0069FF]" href="{{ route('admin.virtual-machines.show', $vm) }}">نمایش</a></td></tr>@empty<tr><td colspan="9" class="px-5 py-10 text-center text-slate-500">VM ثبت نشده است.</td></tr>@endforelse
</tbody></table><div class="border-t border-slate-100 px-5 py-4">{{ $vms->links() }}</div></div>
</div>
@endsection
