@extends('layouts.admin')
@inject('money', 'App\Services\WalletService')
@section('title', 'نمایش VM')
@section('content')
<div class="px-4 py-6 md:px-8 lg:px-10">
@if (session('status'))<div class="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('status') }}</div>@endif
<div class="relative overflow-hidden rounded-2xl bg-[#0A3D37] p-6 text-white shadow-xl shadow-[#0A3D37]/15"><div class="absolute -left-16 -top-16 size-48 rounded-full bg-white/10 blur-2xl"></div><div class="relative flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p class="text-sm font-bold text-emerald-50/60">VM #{{ $vm->id }} · {{ $vm->customer->name }}</p><h1 class="mt-1 text-2xl font-black md:text-4xl" dir="ltr">{{ $vm->name }}</h1><p class="mt-3 leading-8 text-emerald-50/75" dir="ltr">{{ $vm->ip_address ?: 'no-ip' }} · {{ $vm->proxmoxServer?->name ?: 'local only' }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('admin.virtual-machines.edit', $vm) }}" class="rounded-lg bg-white px-5 py-3 text-sm font-black text-[#0A3D37]">ویرایش</a>@if($vm->isRunning())<form method="POST" action="{{ route('admin.virtual-machines.stop', $vm) }}">@csrf <button class="rounded-lg bg-amber-300 px-5 py-3 text-sm font-black text-amber-950">خاموش کردن</button></form>@else<form method="POST" action="{{ route('admin.virtual-machines.start', $vm) }}">@csrf <button class="rounded-lg bg-emerald-300 px-5 py-3 text-sm font-black text-emerald-950">روشن کردن</button></form>@endif</div></div></div>
<section class="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
@foreach([
['label' => 'وضعیت', 'value' => $vm->isRunning() ? 'روشن' : 'خاموش', 'tone' => $vm->isRunning() ? 'text-emerald-700' : 'text-slate-700'],
['label' => 'هزینه ماهانه در وضعیت فعلی', 'value' => $money->format($vm->isRunning() ? $billing->estimateMonthly($vm) : $billing->estimateStoppedMonthly($vm)), 'tone' => 'text-[#105D52]'],
['label' => 'هزینه ماهانه اگر خاموش باشد', 'value' => $money->format($billing->estimateStoppedMonthly($vm)), 'tone' => 'text-amber-700'],
['label' => 'مصرف محاسبه نشده', 'value' => $money->format($billing->currentAccrued($vm)), 'tone' => 'text-slate-950'],
] as $card)<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold text-slate-500">{{ $card['label'] }}</p><p class="mt-3 text-xl font-black {{ $card['tone'] }}">{{ $card['value'] }}</p></div>@endforeach
</section>
<div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-xl font-black">مشخصات سخت‌افزار و Billing</h2><div class="mt-5 grid gap-3 md:grid-cols-4"><div class="rounded-xl bg-slate-50 p-4 text-center"><p class="text-2xl font-black">{{ $vm->cpu_cores }}</p><p class="text-xs text-slate-500">CPU Core فقط روشن</p></div><div class="rounded-xl bg-slate-50 p-4 text-center"><p class="text-2xl font-black">{{ $vm->ram_gb }}GB</p><p class="text-xs text-slate-500">RAM فقط روشن</p></div><div class="rounded-xl bg-slate-50 p-4 text-center"><p class="text-2xl font-black">{{ $vm->disk_gb }}GB</p><p class="text-xs text-slate-500">Disk همیشه</p></div><div class="rounded-xl bg-slate-50 p-4 text-center"><p class="text-2xl font-black">{{ $vm->ip_count }}</p><p class="text-xs text-slate-500">IP همیشه</p></div></div><div class="mt-5 rounded-xl border border-dashed border-slate-300 p-4"><p class="font-black">باندل</p><p class="mt-2 text-sm text-slate-600">{{ $vm->bundle ? $vm->bundle->name . ' - ' . $money->format($vm->bundle->monthly_price) . ' / ماه روشن' : 'Custom pricing از قیمت منابع' }}</p></div></section><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-xl font-black">Proxmox</h2><div class="mt-5 space-y-3 text-sm"><p><span class="font-bold text-slate-500">Server:</span> {{ $vm->proxmoxServer?->name ?: '—' }}</p><p><span class="font-bold text-slate-500">Node:</span> <span dir="ltr">{{ $vm->node ?: '—' }}</span></p><p><span class="font-bold text-slate-500">VMID:</span> <span dir="ltr">{{ $vm->vmid ?: '—' }}</span></p><p><span class="font-bold text-slate-500">Storage:</span> <span dir="ltr">{{ $vm->storage ?: '—' }}</span></p><p><span class="font-bold text-slate-500">OS:</span> <span dir="ltr">{{ $vm->os_template ?: '—' }}</span></p></div></section></div>
</div>
@endsection
