@extends('layouts.admin')
@section('title','پرداخت‌ها')
@section('content')
<div class="px-4 py-6 md:px-8 lg:px-10">
@include('admin.billing._header',['title'=>'پرداخت‌های درگاه','subtitle'=>'تمام تلاش‌های پرداخت، وضعیت نهایی و شناسه‌های تطبیق درگاه.','export'=>'payments'])
@section('extra_filters')<select name="provider" class="rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">همه درگاه‌ها</option>@foreach($providers as $provider)<option @selected(request('provider')===$provider)>{{ $provider }}</option>@endforeach</select>@endsection
@include('admin.billing._filters',['statusOptions'=>['pending'=>'در انتظار','successful'=>'موفق','failed'=>'ناموفق','cancelled'=>'لغو شده']])
<div class="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="px-5 py-3 text-right">مشتری</th><th>درگاه</th><th>مبلغ</th><th>وضعیت</th><th>Authority</th><th>زمان</th><th></th></tr></thead><tbody class="divide-y">@forelse($payments as $payment)<tr><td class="px-5 py-4"><a class="font-black text-slate-900" href="{{ route('admin.customers.show',$payment->customer) }}">{{ $payment->customer?->name }}</a><div class="text-xs text-slate-400">{{ $payment->customer?->email }}</div></td><td>{{ $payment->provider }}</td><td class="font-black">{{ $wallets->format($payment->amount,$payment->currency) }}</td><td>{{ ['pending'=>'در انتظار','successful'=>'موفق','failed'=>'ناموفق','cancelled'=>'لغو شده'][$payment->status] ?? $payment->status }}</td><td dir="ltr">{{ $payment->authority ?: '—' }}</td><td>{{ \Morilog\Jalali\Jalalian::fromCarbon($payment->created_at)->format('Y/m/d H:i') }}</td><td><a class="font-black text-blue-600" href="{{ route('admin.billing.payments.show',$payment) }}">جزئیات</a></td></tr>@empty<tr><td colspan="7" class="p-10 text-center text-slate-500">پرداختی با این فیلترها پیدا نشد.</td></tr>@endforelse</tbody></table></div><div class="border-t p-4">{{ $payments->links() }}</div></div>
</div>@endsection
