server {
    listen 80;
    listen [::]:80;
    server_name aviato.ir my.aviato.ir admin.aviato.ir;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name aviato.ir my.aviato.ir admin.aviato.ir;

    root /var/www/html/aviato/current/public;
    index index.php;

    ssl_certificate /etc/letsencrypt/live/aviato.ir-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aviato.ir-0001/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/aviato-access.log;
    error_log /var/log/nginx/aviato-error.log;

    client_max_body_size 32m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.5-fpm.sock;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_param HTTPS on;
    }

    location ~ /\. {
        deny all;
    }
}
