@extends('customer.layout')
@section('title', 'مصرف شبکه '.$vm->display_name)
@section('header_title', 'مصرف شبکه '.$vm->display_name)
@section('header_subtitle', 'گزارش دوره، سهمیه رایگان و هزینه نهایی‌شده')
@php($activeNav = 'network')
@section('content')
<div class="mb-5 flex flex-wrap gap-2"><a href="{{ route('customer.network.index', [], false) }}" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-black">همه ماشین‌ها</a><a href="{{ route('customer.servers.show', $vm, false) }}" class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">صفحه ماشین</a></div>
@if(!$summary['period'])<div class="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 class="font-black text-amber-900">هنوز داده نهایی دریافت نشده است</h2><p class="mt-2 text-sm leading-7 text-amber-800">نبود داده به معنی مصرف صفر نیست. پس از نهایی‌شدن باکت‌های IPDR، سهمیه و مبلغ اینجا نمایش داده می‌شود.</p></div>@else
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs text-slate-500">ورودی</p><p class="mt-2 text-xl font-black" dir="ltr">{{ $reports->bytes($summary['ingress_bytes']) }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs text-slate-500">خروجی</p><p class="mt-2 text-xl font-black" dir="ltr">{{ $reports->bytes($summary['egress_bytes']) }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs text-slate-500">قابل پرداخت</p><p class="mt-2 text-xl font-black text-amber-600" dir="ltr">{{ $reports->bytes($summary['billable_bytes']) }}</p></div><div class="rounded-2xl border border-[#B8D6FF] bg-[#EBF3FF] p-5"><p class="text-xs text-slate-500">هزینه تخمینی دوره</p><p class="mt-2 text-xl font-black text-[#0069FF]">{{ $wallets->format($summary['accrued_amount']) }}</p></div></div>
<section class="mt-5 rounded-2xl border border-slate-200 bg-white p-6"><div class="flex justify-between"><div><h2 class="font-black">سهمیه ماهانه</h2><p class="mt-1 text-xs text-slate-500">آخرین داده: {{ $summary['latest_bucket']?->interval_end?->diffForHumans() ?? 'نامشخص' }} · ساعات اخیر ممکن است هنوز نهایی نشده باشد.</p></div><b>{{ $summary['usage_percent']===null ? 'بدون سهمیه' : $summary['usage_percent'].'٪' }}</b></div><div class="mt-4 h-3 overflow-hidden rounded-full bg-slate-100"><div class="h-full {{ ($summary['usage_percent']??100)>=100?'bg-amber-500':'bg-[#0069FF]' }}" style="width:{{ min(100,$summary['usage_percent']??100) }}%"></div></div><div class="mt-3 flex flex-wrap justify-between gap-2 text-xs text-slate-500"><span>مصرف: {{ $reports->bytes($summary['rated_bytes']) }}</span><span>باقی‌مانده: {{ $reports->bytes($summary['remaining_bytes']) }}</span><span>سهمیه: {{ $reports->bytes($summary['included_bytes']) }}</span></div></section>
@if($dataState['partial'] || $dataState['missing'])<div class="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{{ $dataState['partial'] }} بازه ناقص و {{ $dataState['missing'] }} بازه مفقود هنوز در مبلغ لحاظ نشده است.</div>@endif
<section class="mt-5 rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-black">مصرف روزانه</h2><div class="mt-5 space-y-4">@forelse($daily as $day)@php($max=max(1,$daily->max(fn($r)=>(int)$r->ingress_bytes+(int)$r->egress_bytes)))@php($total=(int)$day->ingress_bytes+(int)$day->egress_bytes)<div><div class="mb-1 flex justify-between text-xs"><span>{{ $day->usage_date }}</span><span dir="ltr">RX {{ $reports->bytes($day->ingress_bytes) }} · TX {{ $reports->bytes($day->egress_bytes) }}</span></div><div class="h-2 rounded-full bg-slate-100"><div class="h-full rounded-full bg-[#0069FF]" style="width:{{ $total*100/$max }}%"></div></div></div>@empty<p class="py-10 text-center text-sm text-slate-500">مصرف روزانه نهایی‌شده موجود نیست.</p>@endforelse</div></section>@endif
@endsection
