[program:aviato-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/html/aviato/current/artisan schedule:work --whisper
directory=/var/www/html/aviato/current
user=aviato
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=65
redirect_stderr=true
stdout_logfile=/var/log/supervisor/aviato-scheduler.log
stdout_logfile_maxbytes=25MB
stdout_logfile_backups=10
