[program:aviato-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/html/aviato/current/artisan queue:work redis --queue=default --sleep=3 --tries=5 --timeout=900 --max-time=3600 --memory=256 --force
directory=/var/www/html/aviato/current
user=aviato
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=930
redirect_stderr=true
stdout_logfile=/var/log/supervisor/aviato-queue-default.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
