@php($deleteInProgress = $server->isDeleting() && ! $server->delete_failed_at && ! $server->deleteAttemptIsStale())
<div class="mx-auto max-w-4xl space-y-5"><div><h2 class="text-xl font-black text-red-800">حذف سرور</h2><p class="mt-1 text-sm text-slate-500">این عملیات دائمی و غیرقابل بازگشت است.</p></div>
    @if ($deleteInProgress)<div class="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 class="font-black text-amber-900">حذف در حال انجام است</h3><p class="mt-2 text-sm leading-7 text-amber-800">سرور در حال خاموش شدن و حذف است. هزینه آن متوقف شده است.</p></div>@else
        <div class="flex gap-3 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-900"><svg class="mt-0.5 size-6 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m12 3 10 18H2L12 3Zm0 6v5m0 3h.01"/></svg><div><h3 class="font-black">تمام داده‌های سرور حذف می‌شوند</h3><p class="mt-2 text-sm leading-7">پس از حذف موفق، IP رزرو شده آزاد می‌شود. بکاپ‌ها جداگانه نگهداری می‌شوند. از داده‌های لازم پیش از ادامه بکاپ بگیرید.</p></div></div>
        @if ($server->delete_failed_at || $server->deleteAttemptIsStale())<p class="rounded-xl border border-red-200 bg-white p-4 text-sm font-bold text-red-800">حذف قبلی کامل نشد یا بیش از حد منتظر مانده است. می‌توانید دوباره تلاش کنید.</p>@endif
        @if (! $canManageServer)<p class="rounded-xl border border-slate-200 bg-white p-4 text-sm font-bold text-slate-600">برای حذف این سرور دسترسی مدیریت لازم است.</p>@else
        <form action="{{ route('customer.servers.destroy', $server, false) }}" method="POST" class="rounded-2xl border border-red-200 bg-white p-5 shadow-sm" x-data="{ confirmation: @js(old('delete_confirmation', '')), expected: @js($server->display_name), submitting: false }" @submit="submitting = true">@csrf @method('DELETE')
            <h3 class="text-lg font-black">تأیید حذف دائمی</h3><p class="mt-3 text-sm leading-7 text-slate-600">برای حذف دقیقاً نام <strong dir="ltr">{{ $server->display_name }}</strong> را وارد کنید.</p><label for="delete_confirmation" class="mt-5 block text-xs font-black text-slate-600">نام سرور</label><input id="delete_confirmation" name="delete_confirmation" x-model="confirmation" autocomplete="off" spellcheck="false" dir="ltr" placeholder="{{ $server->display_name }}" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm focus:border-red-500 focus:outline-none">
            <div class="mt-5 flex flex-wrap justify-end gap-3"><a href="{{ route('customer.servers.show', $server, false) }}" class="rounded-xl border border-slate-200 px-5 py-3 text-sm font-black text-slate-700">انصراف</a><button type="submit" :disabled="submitting || confirmation.trim() !== expected" class="rounded-xl bg-red-600 px-5 py-3 text-sm font-black text-white hover:bg-red-700 disabled:cursor-not-allowed disabled:opacity-50">{{ $server->delete_failed_at || $server->deleteAttemptIsStale() ? 'تلاش دوباره برای حذف' : 'حذف دائمی سرور' }}</button></div>
        </form>
        @endif
    @endif
</div>
