<div class="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)]" x-data="{ copied: '', reveal: false, copy(value, key) { if (!value) return; navigator.clipboard.writeText(value).then(() => { this.copied = key; setTimeout(() => this.copied = '', 1800); }); } }">
    <div class="space-y-5">
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6">
            <div class="flex items-start justify-between gap-3"><div><p class="text-xs font-black text-[#0069FF]">دسترسی</p><h2 class="mt-1 text-xl font-black text-slate-950">اتصال به سرور</h2></div><span class="rounded-full px-3 py-1.5 text-xs font-black {{ $server->ip_address ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-800' }}">{{ $server->ip_address ? 'IP آماده' : 'در انتظار IP' }}</span></div>
            <div class="mt-5 grid gap-3 sm:grid-cols-2">
                <div class="rounded-xl bg-slate-50 p-4"><p class="text-xs font-bold text-slate-500">نشانی IP</p><div class="mt-2 flex items-center gap-2"><code class="min-w-0 flex-1 truncate text-base font-black" dir="ltr">{{ $server->ip_address ?: '—' }}</code><button type="button" @click="copy(@js($server->ip_address), 'ip')" @disabled(! $server->ip_address) class="rounded-lg bg-white px-2 py-1 text-xs font-black text-[#0069FF] disabled:opacity-40" :aria-label="copied === 'ip' ? 'IP کپی شد' : 'کپی IP'" x-text="copied === 'ip' ? 'کپی شد' : 'کپی'"></button></div></div>
                <div class="rounded-xl bg-slate-50 p-4"><p class="text-xs font-bold text-slate-500">نام کاربری</p><div class="mt-2 flex items-center gap-2"><code class="min-w-0 flex-1 truncate text-base font-black" dir="ltr">{{ $server->login_username ?: '—' }}</code><button type="button" @click="copy(@js($server->login_username), 'user')" @disabled(! $server->login_username) class="rounded-lg bg-white px-2 py-1 text-xs font-black text-[#0069FF] disabled:opacity-40" x-text="copied === 'user' ? 'کپی شد' : 'کپی'" aria-label="کپی نام کاربری"></button></div></div>
            </div>
            @if ($sshCommand)
                <div class="mt-3 flex items-center gap-2 rounded-xl bg-slate-950 p-3 text-white" dir="ltr"><code class="min-w-0 flex-1 truncate text-sm">{{ $sshCommand }}</code><button type="button" @click="copy(@js($sshCommand), 'ssh')" class="shrink-0 rounded-lg bg-white/10 px-3 py-1.5 text-xs font-bold" x-text="copied === 'ssh' ? 'Copied' : 'Copy'" aria-label="کپی فرمان SSH"></button></div>
            @endif
            @if ($credentialDecryptionFailed)
                <p class="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-bold text-amber-800">اطلاعات محرمانه اتصال در حال حاضر قابل نمایش نیست. لطفاً با پشتیبانی تماس بگیرید.</p>
            @elseif ($loginPassword)
                <div class="mt-4 flex flex-wrap items-center gap-2 text-sm"><span class="font-bold text-slate-500">رمز عبور</span><code class="rounded-lg bg-slate-50 px-3 py-2" dir="ltr" x-text="reveal ? @js($loginPassword) : '••••••••'">••••••••</code><button type="button" @click="reveal = !reveal" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold" x-text="reveal ? 'پنهان کردن' : 'نمایش'"></button><button type="button" @click="copy(@js($loginPassword), 'password')" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold" x-text="copied === 'password' ? 'کپی شد' : 'کپی رمز'"></button></div>
            @endif
            @if ($server->ssh_public_key)
                <details class="mt-4 rounded-xl border border-slate-200 p-4"><summary class="cursor-pointer text-sm font-black">کلید عمومی SSH</summary><code class="mt-3 block break-all text-xs" dir="ltr">{{ $server->ssh_public_key }}</code><button type="button" @click="copy(@js($server->ssh_public_key), 'key')" class="mt-3 rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold text-[#0069FF]" x-text="copied === 'key' ? 'کپی شد' : 'کپی کلید'" aria-label="کپی کلید عمومی SSH"></button></details>
            @endif
        </section>
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><h2 class="text-lg font-black">وضعیت سرویس</h2><div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs text-slate-500">قدرت</p><p class="mt-1 font-black">{{ $statusLabel }}</p></div><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs text-slate-500">آماده سازی</p><p class="mt-1 font-black">{{ $provisioningLabel }}</p></div><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs text-slate-500">آخرین تغییر</p><p class="mt-1 text-sm font-black" dir="ltr">{{ \App\Support\Jalali::format($server->updated_at) }}</p></div></div></section>
    </div>
    <div class="space-y-5">
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-black">خلاصه منابع</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><dt class="text-slate-500">پردازنده</dt><dd class="font-black" dir="ltr">{{ $server->cpu_cores }} CPU</dd></div><div class="flex justify-between"><dt class="text-slate-500">حافظه</dt><dd class="font-black" dir="ltr">{{ $server->ram_gb }} GB</dd></div><div class="flex justify-between"><dt class="text-slate-500">دیسک اصلی</dt><dd class="font-black" dir="ltr">{{ $server->disk_gb }} GB</dd></div><div class="flex justify-between border-t border-slate-100 pt-3"><dt class="text-slate-500">هزینه ماهانه تخمینی</dt><dd class="font-black text-[#0069FF]">{{ $server->isDeleting() ? 'متوقف شده' : $wallets->format($monthlyCost) }}</dd></div></dl><a href="{{ route('customer.servers.tab', [$server, 'tab' => 'resources'], false) }}" class="mt-5 inline-block text-sm font-black text-[#0069FF]">مشاهده منابع ←</a></section>
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-black">بکاپ</h2><p class="mt-2 text-sm text-slate-600">{{ $backupSummary['enabled'] ? 'برنامه بکاپ فعال است.' : 'برنامه بکاپ خودکار فعال نیست.' }}</p><p class="mt-2 text-xs text-slate-500">آخرین نسخه: {{ $backupSummary['latest_at'] ? \App\Support\Jalali::format($backupSummary['latest_at']) : 'ثبت نشده' }}</p><a href="{{ route('customer.backups.index', [], false) }}" class="mt-4 inline-block text-sm font-black text-[#0069FF]">مدیریت بکاپ‌ها ←</a></section>
    </div>
</div>
