@php
    $isRebuilding = $server->provisioning_status === \App\Models\VirtualMachine::PROVISION_PENDING && filled(data_get($server->remote_state, 'rebuild_started_at'));
    $hasInfrastructure = $server->isHetzner()
        ? ($server->infrastructureLocation?->hetznerAccount && $server->remote_id && $server->cloudImage?->remote_image_id)
        : ($server->proxmoxServer && $server->node && $server->vmid && $server->template_vmid);
    $canRebuild = $canManageServer && ! $server->isActionLocked() && $server->provisioning_status !== \App\Models\VirtualMachine::PROVISION_PENDING && ! $hasPendingUpgrade && $server->cloudImage?->is_active && $hasInfrastructure;
@endphp
<div class="mx-auto max-w-4xl space-y-5"><div><h2 class="text-xl font-black text-slate-950">بازسازی سیستم عامل</h2><p class="mt-1 text-sm text-slate-500">نصب دوباره سیستم عامل روی همین سرور، با IP و منابع فعلی</p></div>
    <div class="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><svg class="mt-0.5 size-6 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m12 3 10 18H2L12 3Zm0 6v5m0 3h.01"/></svg><div><h3 class="font-black">داده‌های دیسک اصلی پاک می‌شوند</h3><p class="mt-2 text-sm leading-7">قبل از ادامه بکاپ لازم را تهیه کنید. IP و منابع حفظ می‌شوند؛ بکاپ‌ها و دیسک‌های اضافه جداگانه باقی می‌مانند.</p></div></div>
    @if ($isRebuilding)<p class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm font-bold text-[#031B4E]">بازسازی در حال انجام است. پس از پایان، وضعیت سرور به‌روز می‌شود.</p>@elseif (data_get($server->remote_state, 'rebuild_error'))<p class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-800">بازسازی قبلی کامل نشد. می‌توانید پس از بررسی شرایط دوباره تلاش کنید یا با پشتیبانی تماس بگیرید.</p>@endif
    @unless ($canRebuild)<p class="rounded-xl bg-slate-100 p-4 text-sm font-bold text-slate-700">بازسازی زمانی در دسترس است که سرور آماده باشد، تصویر فعال باشد و عملیات دیگری در جریان نباشد.</p>@endunless
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="text-lg font-black">جزئیات</h3><dl class="mt-4 grid gap-4 sm:grid-cols-2 text-sm"><div><dt class="text-slate-500">سیستم عامل</dt><dd class="mt-1 font-black">{{ $server->cloudImage?->name ?: '—' }}</dd></div><div><dt class="text-slate-500">هزینه بازسازی</dt><dd class="mt-1 font-black">{{ $rebuildFee > 0 ? $wallets->format($rebuildFee) : 'بدون هزینه' }}</dd></div></dl></section>
    <form action="{{ route('customer.servers.rebuild', $server, false) }}" method="POST" class="space-y-5" x-data="{ acknowledged: false, confirmation: @js(old('rebuild_confirmation', '')), expected: @js($server->display_name), submitting: false }" @submit="submitting = true">@csrf
        @if ($server->cloudImage?->cloud_init_enabled)<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="text-lg font-black">اطلاعات ورود جدید</h3><p class="mt-2 text-sm text-slate-500">فیلدهای خالی طبق اطلاعات فعلی سرور تکمیل می‌شوند.</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="block text-xs font-bold text-slate-600">Hostname<input value="{{ $server->hostname ?: $server->name }}" dir="ltr" readonly class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600"></label><label class="block text-xs font-bold text-slate-600">Username<input name="login_username" value="{{ old('login_username', $server->login_username ?: $server->cloudImage?->default_username) }}" dir="ltr" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm focus:border-[#0069FF] focus:outline-none" @disabled(!$canRebuild)></label><label class="block text-xs font-bold text-slate-600 sm:col-span-2">رمز عبور جدید<input name="login_password" type="password" minlength="8" autocomplete="new-password" dir="ltr" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm focus:border-[#0069FF] focus:outline-none" @disabled(!$canRebuild)><span class="mt-1 block text-xs text-slate-500">خالی بماند، رمز فعلی حفظ می‌شود؛ اگر رمز و کلید SSH موجود نباشد، رمز امن ساخته می‌شود.</span></label><label class="block text-xs font-bold text-slate-600 sm:col-span-2">کلید عمومی SSH<textarea name="ssh_public_key" rows="3" dir="ltr" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm focus:border-[#0069FF] focus:outline-none" @disabled(!$canRebuild)>{{ old('ssh_public_key', $server->ssh_public_key) }}</textarea></label></div></section>@endif
        <section class="rounded-2xl border border-amber-200 bg-amber-50/50 p-5"><label class="flex items-start gap-3 text-sm font-bold leading-7"><input type="checkbox" x-model="acknowledged" class="mt-1" @disabled(!$canRebuild)><span>می‌دانم که داده‌های دیسک اصلی پاک می‌شوند و بازگشت فقط از بکاپ ممکن است.</span></label><label class="mt-5 block text-xs font-bold text-slate-600">نام سرور را برای تأیید وارد کنید<input name="rebuild_confirmation" x-model="confirmation" autocomplete="off" spellcheck="false" dir="ltr" placeholder="{{ $server->display_name }}" class="mt-2 w-full rounded-xl border border-amber-200 bg-white px-4 py-3 text-sm focus:border-amber-600 focus:outline-none" @disabled(!$canRebuild)></label><div class="mt-5 flex justify-end"><button type="submit" :disabled="submitting || !acknowledged || confirmation.trim() !== expected" @disabled(!$canRebuild) class="rounded-xl bg-amber-600 px-5 py-3 text-sm font-black text-white hover:bg-amber-700 disabled:cursor-not-allowed disabled:opacity-50">شروع بازسازی</button></div></section>
    </form>
</div>
