<div class="space-y-5"><div><h2 class="text-xl font-black text-slate-950">منابع سرور</h2><p class="mt-1 text-sm text-slate-500">مشخصات فعلی سخت‌افزار و فضای ذخیره‌سازی</p></div>
    <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        @foreach ([['پردازنده', $server->cpu_cores.' CPU', 'cpu'], ['حافظه', $server->ram_gb.' GB', 'ram'], ['دیسک اصلی', $server->disk_gb.' GB', 'disk'], ['نشانی IP', $server->ip_address ?: 'در انتظار', 'ip']] as $metric)
            <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold text-slate-500">{{ $metric[0] }}</p><p class="mt-3 truncate text-xl font-black text-slate-950" dir="ltr">{{ $metric[1] }}</p></div>
        @endforeach
    </section>
    <section class="grid gap-5 lg:grid-cols-2"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="text-lg font-black">پیکربندی</h3><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-3"><dt class="text-slate-500">پلن</dt><dd class="font-black">{{ $server->bundle?->name ?: 'اختصاصی' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">سیستم عامل</dt><dd class="font-black">{{ $server->cloudImage?->name ?: $server->os_template ?: '—' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">موقعیت</dt><dd class="font-black">{{ $server->infrastructureLocation?->name ?: $server->proxmoxServer?->name ?: '—' }}</dd></div></dl></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="text-lg font-black">دیسک‌های اضافه</h3><div class="mt-4 space-y-3">@forelse ($server->disks as $disk)<div class="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-4 text-sm"><span class="font-black" dir="ltr">{{ $disk->size_gb }} GB · {{ $disk->disk_device }}</span><span class="rounded-full px-2 py-1 text-xs font-bold {{ $disk->status === 'ready' ? 'bg-emerald-50 text-emerald-700' : ($disk->status === 'failed' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-800') }}">{{ $disk->status === 'ready' ? 'آماده' : ($disk->status === 'failed' ? 'ناموفق' : 'در حال آماده‌سازی') }}</span></div>@empty<p class="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">دیسک اضافه‌ای ثبت نشده است.</p>@endforelse</div></div></section>
    <a href="{{ route('customer.servers.tab', [$server, 'tab' => 'upgrade'], false) }}" class="inline-flex rounded-xl bg-[#0069FF] px-5 py-3 text-sm font-black text-white hover:bg-[#0050D0]">ارتقای منابع</a>
</div>
