@php($upgradeBlocked = ! $canManageServer || $server->isActionLocked() || $server->provisioning_status !== \App\Models\VirtualMachine::PROVISION_READY || $hasPendingUpgrade)
<div class="space-y-5"><div><h2 class="text-xl font-black text-slate-950">ارتقای منابع</h2><p class="mt-1 text-sm text-slate-500">پلن سرور یا فضای ذخیره‌سازی را افزایش دهید.</p></div>
    @if ($upgradeBlocked)<div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">{{ $hasPendingUpgrade ? 'یک ارتقا در حال انجام است. بعد از پایان آن دوباره تلاش کنید.' : 'ارتقا زمانی در دسترس است که سرور آماده باشد و عملیات دیگری روی آن انجام نشود.' }}</div>@endif
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="text-lg font-black">پلن فعلی</h3><p class="mt-3 text-sm font-bold text-slate-700">{{ $server->bundle?->name ?: 'اختصاصی' }} · <span dir="ltr">{{ $server->cpu_cores }} CPU / {{ $server->ram_gb }} GB RAM / {{ $server->disk_gb }} GB Disk</span></p></section>
    <div class="grid gap-5 xl:grid-cols-2">
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="text-lg font-black">ارتقای پلن</h3><p class="mt-2 text-sm leading-7 text-slate-500">سرور برای اعمال منابع جدید خاموش و دوباره روشن می‌شود. هزینه جدید پس از اعمال موفق محاسبه خواهد شد.</p>
            @if ($eligibleBundles->isNotEmpty())<form method="POST" action="{{ route('customer.servers.upgrades.bundle.store', $server, false) }}" class="mt-5 space-y-4" x-data="{ submitting: false }" @submit="submitting = true">@csrf
                <label for="vm_bundle_id" class="block text-sm font-bold">پلن جدید</label><select id="vm_bundle_id" name="vm_bundle_id" required @disabled($upgradeBlocked) class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm focus:border-[#0069FF] focus:outline-none disabled:opacity-50">@foreach ($eligibleBundles as $bundle)<option value="{{ $bundle->id }}" @selected(old('vm_bundle_id') == $bundle->id)>{{ $bundle->name }} · {{ $bundle->cpu_cores }} CPU / {{ $bundle->ram_gb }} GB RAM · +{{ $wallets->format($bundlePreviews[$bundle->id]['monthly_delta']) }}/ماه</option>@endforeach</select>
                @error('vm_bundle_id')<p class="text-sm text-red-700">{{ $message }}</p>@enderror
                <p class="rounded-xl bg-[#EEF5FF] p-3 text-xs leading-6 text-[#031B4E]">برای شروع ارتقا، موجودی کیف پول مالک فضا باید حداقل ۲۴ ساعت هزینه پلن جدید را پوشش دهد.</p>
                <button type="submit" :disabled="submitting" @disabled($upgradeBlocked) class="rounded-xl bg-[#0069FF] px-5 py-3 text-sm font-black text-white hover:bg-[#0050D0] disabled:cursor-not-allowed disabled:opacity-50">ثبت ارتقای پلن</button>
            </form>@else<p class="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">پلن بالاتری برای این سرور در دسترس نیست.</p>@endif
        </section>
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="text-lg font-black">دیسک اضافه</h3><p class="mt-2 text-sm leading-7 text-slate-500">پس از اتصال دیسک، باید آن را در سیستم عامل mount کنید.</p>
            @if ($extraDiskOptions->isNotEmpty())<form method="POST" action="{{ route('customer.servers.upgrades.extra-disk.store', $server, false) }}" class="mt-5 space-y-4" x-data="{ submitting: false }" @submit="submitting = true">@csrf
                <label for="size_gb" class="block text-sm font-bold">اندازه دیسک</label><select id="size_gb" name="size_gb" required @disabled($upgradeBlocked) class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm focus:border-[#0069FF] focus:outline-none disabled:opacity-50">@foreach ($extraDiskOptions as $option)<option value="{{ $option['size_gb'] }}" @selected(old('size_gb') == $option['size_gb'])>{{ $option['size_gb'] }} GB · +{{ $wallets->format($option['monthly_delta']) }}/ماه</option>@endforeach</select>
                @error('size_gb')<p class="text-sm text-red-700">{{ $message }}</p>@enderror
                <button type="submit" :disabled="submitting" @disabled($upgradeBlocked) class="rounded-xl border border-[#0069FF] px-5 py-3 text-sm font-black text-[#0069FF] hover:bg-[#EEF5FF] disabled:cursor-not-allowed disabled:opacity-50">افزودن دیسک</button>
            </form>@else<p class="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">افزودن دیسک برای این سرور در دسترس نیست.</p>@endif
        </section>
    </div>
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="text-lg font-black">تاریخچه ارتقا</h3><div class="mt-4 divide-y divide-slate-100">@forelse ($server->upgradeOrders as $order)<div class="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><div><p class="font-black">{{ $order->type === 'bundle' ? 'ارتقای پلن به '.$order->toBundle?->name : 'دیسک اضافه '.($order->after_snapshot['size_gb'] ?? '').' GB' }}</p><p class="mt-1 text-xs text-slate-500">{{ \App\Support\Jalali::format($order->created_at) }} · افزایش ماهانه {{ $wallets->format($order->estimated_monthly_delta) }}</p></div><span class="rounded-full px-3 py-1 text-xs font-bold {{ $order->status === 'succeeded' ? 'bg-emerald-50 text-emerald-700' : ($order->status === 'failed' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-800') }}">{{ $order->status === 'succeeded' ? 'انجام شد' : ($order->status === 'failed' ? 'ناموفق' : 'در حال بررسی') }}</span></div>@empty<p class="py-4 text-sm text-slate-500">هنوز ارتقایی ثبت نشده است.</p>@endforelse</div></section>
</div>
