@extends('layouts.admin')
@section('title','کمپین جدید')
@section('content')
<div class="mx-auto max-w-5xl px-4 py-6 md:px-8"><a href="{{ route('admin.promotions.index') }}" class="text-sm font-black text-[#0069FF]">بازگشت</a><form method="POST" action="{{ route('admin.promotions.store') }}" class="mt-4 space-y-6 rounded-2xl border bg-white p-6 shadow-sm" x-data="{type:@js(old('type','wallet_credit')),audience:@js(old('audience','all'))}">@csrf
<div><h1 class="text-2xl font-black">ساخت کمپین کارت هدیه</h1><p class="mt-2 text-sm text-slate-500">بعد از تولید کدها، قواعد مالی و مخاطبان قفل می‌شوند.</p></div>
<div class="grid gap-4 md:grid-cols-2"><label class="text-sm font-black">نام کمپین<input name="name" value="{{ old('name') }}" required class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label><label class="text-sm font-black">نوع<select name="type" x-model="type" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"><option value="wallet_credit">اعتبار مستقیم</option><option value="top_up_percentage">پاداش درصدی شارژ</option></select></label><label class="text-sm font-black">مخاطب<select name="audience" x-model="audience" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"><option value="all">همه دارندگان کد</option><option value="new_customer">مشتری بدون شارژ موفق</option><option value="allowlist">فهرست مجاز</option></select></label><label class="text-sm font-black">تعداد کد<input name="code_count" type="number" min="1" max="25000" value="{{ old('code_count',100) }}" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label></div>
<div x-show="type==='wallet_credit'"><label class="text-sm font-black">اعتبار هر کارت (تومان)<input name="credit_amount_toman" type="number" value="{{ old('credit_amount_toman') }}" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label></div>
<div x-show="type==='top_up_percentage'" class="grid gap-4 md:grid-cols-3"><label class="text-sm font-black">درصد پاداش<input name="percentage" type="number" min="1" max="100" value="{{ old('percentage') }}" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label><label class="text-sm font-black">حداقل شارژ (تومان)<input name="minimum_top_up_toman" type="number" value="{{ old('minimum_top_up_toman') }}" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label><label class="text-sm font-black">سقف پاداش (تومان)<input name="maximum_bonus_toman" type="number" value="{{ old('maximum_bonus_toman') }}" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label></div>
<div class="grid gap-4 md:grid-cols-2"><label class="text-sm font-black">شروع (اختیاری)<input name="starts_at" type="datetime-local" value="{{ old('starts_at') }}" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label><label class="text-sm font-black">انقضا<input name="expires_at" type="datetime-local" required value="{{ old('expires_at',$defaultExpiry) }}" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label></div>
<div class="grid gap-4"><label class="text-sm font-black">عنوان روی کارت<input name="headline" value="{{ old('headline') }}" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal"></label><label class="text-sm font-black">پیام<textarea name="message" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal">{{ old('message') }}</textarea></label><label class="text-sm font-black">شرایط کوتاه<textarea name="terms" class="mt-2 w-full rounded-xl border px-4 py-3 font-normal">{{ old('terms') }}</textarea></label></div>
@if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm font-bold text-rose-700">{{ $errors->first() }}</div>@endif<button class="rounded-xl bg-[#0069FF] px-6 py-3 font-black text-white">ساخت پیش‌نویس</button></form></div>
@endsection
