@extends('layouts.admin')
@section('title','پروموشن و کارت هدیه')
@section('content')
<div class="px-4 py-6 md:px-8 lg:px-10">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-2xl font-black">پروموشن و کارت هدیه</h1><p class="mt-1 text-sm text-slate-500">صدور، چاپ، کنترل تعهد و پایش استفاده از کدهای یک‌بارمصرف.</p></div><a href="{{ route('admin.promotions.create') }}" class="rounded-xl bg-[#0069FF] px-5 py-3 text-center text-sm font-black text-white">کمپین جدید</a></div>
    <form class="mt-5 flex flex-wrap gap-3 rounded-xl border bg-white p-4"><input name="q" value="{{ request('q') }}" placeholder="نام کمپین" class="min-w-56 flex-1 rounded-lg border px-3 py-2.5"><select name="status" class="rounded-lg border px-3"><option value="">همه وضعیت‌ها</option>@foreach(['draft'=>'پیش‌نویس','scheduled'=>'زمان‌بندی','active'=>'فعال','paused'=>'متوقف','ended'=>'پایان‌یافته'] as $k=>$v)<option value="{{ $k }}" @selected(request('status')===$k)>{{ $v }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-5 text-white">اعمال</button></form>
    <div class="mt-5 overflow-x-auto rounded-xl border bg-white"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="p-4 text-right">کمپین</th><th>نوع</th><th>وضعیت</th><th>کد / استفاده</th><th>تعهد حداکثری</th><th>انقضا</th><th></th></tr></thead><tbody class="divide-y">@forelse($campaigns as $campaign)<tr><td class="p-4"><b>{{ $campaign->name }}</b><p class="font-mono text-xs text-slate-400" dir="ltr">{{ $campaign->public_id }}</p></td><td>{{ $campaign->type==='wallet_credit'?'اعتبار مستقیم':'پاداش درصدی' }}</td><td><x-admin.status-badge :value="$campaign->status" /></td><td>{{ number_format($campaign->codes_count) }} / {{ number_format($campaign->redemptions_count) }}</td><td class="font-black">{{ $wallets->format($campaign->maximum_liability) }}</td><td>{{ \Morilog\Jalali\Jalalian::fromCarbon($campaign->expires_at)->format('Y/m/d H:i') }}</td><td><a href="{{ route('admin.promotions.show',$campaign) }}" class="font-black text-[#0069FF]">مدیریت</a></td></tr>@empty<tr><td colspan="7" class="p-12 text-center text-slate-500">کمپینی ساخته نشده است.</td></tr>@endforelse</tbody></table><div class="border-t p-4">{{ $campaigns->links() }}</div></div>
</div>
@endsection
