@extends('layouts.admin')
@section('title',$campaign->name)
@section('content')
<div class="px-4 py-6 md:px-8 lg:px-10"><div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><a href="{{ route('admin.promotions.index') }}" class="text-sm font-black text-[#0069FF]">بازگشت</a><h1 class="mt-2 text-2xl font-black">{{ $campaign->name }}</h1><p class="mt-1 text-sm text-slate-500">{{ $campaign->type==='wallet_credit'?$wallets->format($campaign->credit_amount).' اعتبار برای هر کد':$campaign->percentage.'٪ پاداش؛ سقف '.$wallets->format($campaign->maximum_bonus) }}</p></div><div class="flex flex-wrap gap-2">@if(!$campaign->rules_locked_at)<form method="POST" action="{{ route('admin.promotions.generate',$campaign) }}">@csrf<button class="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-black text-white">تولید {{ number_format($campaign->code_count) }} کد</button></form>@elseif(in_array($campaign->status,['draft','scheduled']))<form method="POST" action="{{ route('admin.promotions.activate',$campaign) }}">@csrf<button class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">فعال‌سازی</button></form>@endif @if($campaign->status==='active')<form method="POST" action="{{ route('admin.promotions.pause',$campaign) }}">@csrf<button class="rounded-xl bg-amber-500 px-4 py-2.5 text-sm font-black text-white">توقف</button></form>@elseif($campaign->status==='paused')<form method="POST" action="{{ route('admin.promotions.resume',$campaign) }}">@csrf<button class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">ادامه</button></form>@endif @if($campaign->rules_locked_at)<a href="{{ route('admin.promotions.print',$campaign) }}" class="rounded-xl bg-[#0069FF] px-4 py-2.5 text-sm font-black text-white">چاپ کارت‌ها</a>@endif</div></div>
<div class="mt-6 grid gap-3 sm:grid-cols-4">@foreach([['وضعیت',$campaign->status],['کدها',$campaign->codes_count],['استفاده‌شده',$campaign->redemptions_count],['تعهد',$wallets->format($campaign->maximum_liability)]] as [$l,$v])<div class="rounded-xl border bg-white p-4"><p class="text-xs text-slate-500">{{ $l }}</p><p class="mt-2 font-black">{{ $v }}</p></div>@endforeach</div>
@if($campaign->audience==='allowlist'&&!$campaign->rules_locked_at)<form method="POST" enctype="multipart/form-data" action="{{ route('admin.promotions.allowlist',$campaign) }}" class="mt-5 rounded-xl border bg-white p-5">@csrf<h2 class="font-black">فهرست مجاز</h2><p class="mt-1 text-xs text-slate-500">شناسه، ایمیل یا موبایل؛ هر مورد در یک خط، یا فایل CSV.</p><div class="mt-3 grid gap-3 md:grid-cols-[1fr_280px_auto]"><textarea name="identifiers" class="rounded-xl border p-3" placeholder="customer@example.com"></textarea><input type="file" name="csv" accept=".csv,.txt" class="rounded-xl border p-3"><button class="rounded-xl bg-slate-900 px-5 font-black text-white">افزودن</button></div></form>@endif
<form method="POST" action="{{ route('admin.promotions.copy.update',$campaign) }}" class="mt-5 grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3">@csrf @method('PATCH')<input name="headline" value="{{ $campaign->headline }}" placeholder="عنوان کارت" class="rounded-xl border px-3 py-2"><input name="message" value="{{ $campaign->message }}" placeholder="پیام" class="rounded-xl border px-3 py-2"><div class="flex gap-2"><input name="terms" value="{{ $campaign->terms }}" placeholder="شرایط" class="min-w-0 flex-1 rounded-xl border px-3 py-2"><button class="rounded-xl bg-slate-900 px-4 text-white">ذخیره متن</button></div></form>
<div class="mt-5 overflow-x-auto rounded-xl border bg-white"><table class="min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-3 text-right">کد</th><th>وضعیت</th><th>رزرو تا</th><th>استفاده</th></tr></thead><tbody class="divide-y">@forelse($codes as $code)<tr><td class="p-3 font-mono font-black" dir="ltr">{{ $code->encrypted_code }}</td><td>{{ $code->status }}</td><td>{{ $code->reserved_until?->format('Y-m-d H:i')?:'—' }}</td><td>{{ $code->redeemed_at?->format('Y-m-d H:i')?:'—' }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center">هنوز کدی تولید نشده است.</td></tr>@endforelse</tbody></table><div class="border-t p-4">{{ $codes->links() }}</div></div>
@if($campaign->rules_locked_at)<div class="mt-5 flex flex-wrap gap-3"><a href="{{ route('admin.promotions.exceptions',$campaign) }}" class="rounded-xl border px-4 py-2 font-black text-amber-700">استثناهای پرداخت</a><form method="POST" action="{{ route('admin.promotions.revoke-unused',$campaign) }}" onsubmit="return confirm('تمام کدهای استفاده‌نشده باطل و کمپین پایان یابد؟')">@csrf<button class="rounded-xl border border-rose-200 px-4 py-2 font-black text-rose-700">ابطال کدهای استفاده‌نشده</button></form></div>@endif</div>
@endsection
