@extends('layouts.admin')
@section('title', 'کاربران پنل')
@section('content')
<div class="px-4 py-6 md:px-8 lg:px-10">
    @if(session('status'))<div class="mb-5 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{{ session('status') }}</div>@endif
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-2xl font-black">کاربران پنل</h1><p class="mt-2 text-sm text-slate-500">مدیریت نقش، وضعیت و نشست‌های کارکنان</p></div><a href="{{ route('admin.users.create') }}" class="rounded-xl bg-[#0069FF] px-5 py-3 text-center text-sm font-black text-white">افزودن کاربر</a></div>
    <form class="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-4"><input name="q" value="{{ request('q') }}" placeholder="نام، ایمیل یا موبایل" class="rounded-xl border border-slate-200 px-4 py-3 md:col-span-2"><select name="role" class="rounded-xl border border-slate-200 px-4 py-3"><option value="">همه نقش‌ها</option>@foreach($roles as $value=>$label)<option value="{{ $value }}" @selected(request('role')===$value)>{{ $label }}</option>@endforeach</select><select name="status" class="rounded-xl border border-slate-200 px-4 py-3"><option value="">همه وضعیت‌ها</option><option value="active" @selected(request('status')==='active')>فعال</option><option value="inactive" @selected(request('status')==='inactive')>غیرفعال</option></select><button class="rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white">اعمال فیلتر</button></form>
    <div class="mt-5 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="px-5 py-3 text-right">کاربر</th><th>نقش</th><th>وضعیت</th><th>آخرین ورود</th><th>تیکت‌ها</th><th></th></tr></thead><tbody class="divide-y">@forelse($users as $user)<tr><td class="px-5 py-4"><b>{{ $user->name }}</b><p class="mt-1 text-xs text-slate-400" dir="ltr">{{ $user->email ?: $user->phone }}</p></td><td>{{ $user->role->label() }}</td><td><span class="rounded-full px-3 py-1 text-xs font-black {{ $user->is_active ? 'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700' }}">{{ $user->is_active ? 'فعال':'غیرفعال' }}</span></td><td>{{ $user->last_login_at ? \Morilog\Jalali\Jalalian::fromCarbon($user->last_login_at)->format('Y/m/d H:i') : 'هرگز' }}</td><td>{{ $user->assigned_tickets_count }}</td><td class="px-5"><a href="{{ route('admin.users.show',$user) }}" class="font-black text-[#0069FF]">جزئیات</a></td></tr>@empty<tr><td colspan="6" class="p-12 text-center text-slate-500">کاربری پیدا نشد.</td></tr>@endforelse</tbody></table><div class="border-t p-4">{{ $users->links() }}</div></div>
</div>
@endsection
