@extends('layouts.admin')
@section('title', 'اتصال IPDR')
@section('content')
<div class="px-4 py-6 md:px-8 lg:px-10"><h1 class="text-2xl font-black">اتصال IPDR</h1><p class="mt-2 text-sm text-slate-500">توکن هیچ‌گاه در UI نمایش داده نمی‌شود.</p><div class="mt-5">@include('admin.billing.network._nav')</div>
@if(session('status'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('status') }}</div>@endif
@if(session('error'))<div class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-800" dir="ltr">{{ session('error') }}</div>@endif
<div class="grid gap-6 lg:grid-cols-2"><section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-black">وضعیت پیکربندی</h2><dl class="mt-5 space-y-4 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-500">URL</dt><dd class="font-mono" dir="ltr">{{ $baseUrl ?: 'تنظیم نشده' }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Source</dt><dd class="font-mono">{{ $source }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">توکن</dt><dd class="font-black {{ $configured ? 'text-emerald-600' : 'text-red-600' }}">{{ $configured ? 'پیکربندی شده' : 'ناقص' }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">آخرین تلاش</dt><dd>{{ $checkpoint?->last_attempted_at?->diffForHumans() ?? 'هرگز' }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">آخرین موفقیت</dt><dd>{{ $checkpoint?->last_succeeded_at?->diffForHumans() ?? 'هرگز' }}</dd></div></dl><form method="POST" action="{{ route('admin.billing.network.ipdr.test') }}" class="mt-5">@csrf<button class="w-full rounded-xl border border-[#0069FF] px-4 py-3 text-sm font-black text-[#0069FF] disabled:cursor-not-allowed disabled:opacity-50" @disabled(!$configured)>آزمایش اتصال</button></form>@if($checkpoint?->last_error)<div class="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700" dir="ltr">{{ $checkpoint->last_error }}</div>@endif</section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-black">همگام‌سازی و Backfill</h2><p class="mt-2 text-xs text-slate-500">درخواست در صف اجرا می‌شود و صفحه منتظر IPDR نمی‌ماند. تکرار داده هزینه دوباره ایجاد نمی‌کند.</p><form method="POST" action="{{ route('admin.billing.network.sync') }}" class="mt-5 space-y-4">@csrf<div><label class="text-xs font-black text-slate-600">از تاریخ UTC (اختیاری)</label><input name="from" type="datetime-local" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" dir="ltr"></div><div><label class="text-xs font-black text-slate-600">تا تاریخ UTC (اختیاری)</label><input name="to" type="datetime-local" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" dir="ltr"></div><button class="w-full rounded-xl bg-[#0069FF] px-4 py-3 text-sm font-black text-white">قرار دادن در صف</button></form></section></div></div>
@endsection
