@extends('layouts.admin')
@section('title', 'مصرف شبکه '.$vm->display_name)
@section('content')
<div class="px-4 py-6 md:px-8 lg:px-10"><div class="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><a href="{{ route('admin.billing.network.index') }}" class="text-sm font-black text-[#0069FF]">حسابداری شبکه ←</a><h1 class="mt-2 text-2xl font-black">{{ $vm->display_name }}</h1><p class="mt-1 font-mono text-xs text-slate-400" dir="ltr">{{ $vm->uuid }}</p></div><div class="flex gap-2"><a href="{{ route('admin.virtual-machines.edit', $vm) }}" class="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-black">تنظیم override</a><a href="{{ route('admin.virtual-machines.show', $vm) }}" class="rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white">جزئیات ماشین</a></div></div>
@if(!$summary['period'])<div class="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-800"><h2 class="font-black">دوره حسابداری ایجاد نشده است</h2><p class="mt-2 text-sm">تا وقتی یک باکت final و complete برای سیاست فعال دریافت نشود، مصرف صفر نمایش داده نمی‌شود و مبلغی محاسبه نخواهد شد.</p></div>@else
<div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs font-black text-slate-500">ورودی</p><p class="mt-3 text-xl font-black" dir="ltr">{{ $reports->bytes($summary['ingress_bytes']) }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs font-black text-slate-500">خروجی</p><p class="mt-3 text-xl font-black" dir="ltr">{{ $reports->bytes($summary['egress_bytes']) }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs font-black text-slate-500">مصرف قابل پرداخت</p><p class="mt-3 text-xl font-black text-amber-600" dir="ltr">{{ $reports->bytes($summary['billable_bytes']) }}</p></div><div class="rounded-2xl border border-[#B8D6FF] bg-[#EBF3FF] p-5"><p class="text-xs font-black text-slate-500">هزینه دوره</p><p class="mt-3 text-xl font-black text-[#0069FF]">{{ $wallets->format($summary['accrued_amount']) }}</p></div></div>
<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><div class="flex items-center justify-between"><div><h2 class="font-black">پیشرفت سهمیه</h2><p class="mt-1 text-xs text-slate-500">{{ $summary['period']->direction }} · {{ $wallets->format($summary['period']->price_per_unit) }} بر {{ $reports->bytes($summary['period']->price_unit_bytes) }}</p></div><span class="text-lg font-black">{{ $summary['usage_percent'] === null ? 'بدون سهمیه' : $summary['usage_percent'].'٪' }}</span></div><div class="mt-4 h-3 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full {{ ($summary['usage_percent'] ?? 100) >= 100 ? 'bg-amber-500' : 'bg-[#0069FF]' }}" style="width: {{ min(100, $summary['usage_percent'] ?? 100) }}%"></div></div><div class="mt-3 flex justify-between text-xs text-slate-500"><span>مصرف: {{ $reports->bytes($summary['rated_bytes']) }}</span><span>باقی‌مانده: {{ $reports->bytes($summary['remaining_bytes']) }}</span><span>سهمیه: {{ $reports->bytes($summary['included_bytes']) }}</span></div></section>
@endif
<div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-black">مصرف روزانه</h2><div class="mt-5 space-y-3">@forelse($daily as $day)@php($max=max(1,$daily->max(fn($r)=>(int)$r->ingress_bytes+(int)$r->egress_bytes)))@php($total=(int)$day->ingress_bytes+(int)$day->egress_bytes)<div><div class="mb-1 flex justify-between text-xs"><span>{{ $day->usage_date }}</span><span dir="ltr">{{ $reports->bytes($total) }}</span></div><div class="h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full bg-[#0069FF]" style="width: {{ $total*100/$max }}%"></div></div></div>@empty<p class="py-10 text-center text-sm text-slate-500">داده نهایی روزانه موجود نیست.</p>@endforelse</div></section><section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-black">سیاست snapshot شده</h2>@if($summary['period'])<dl class="mt-5 space-y-4 text-sm"><div class="flex justify-between"><dt class="text-slate-500">دوره</dt><dd dir="ltr">{{ $summary['period']->period_start }} — {{ $summary['period']->period_end }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">منطقه زمانی</dt><dd>{{ $summary['period']->timezone }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">جهت محاسبه</dt><dd>{{ $summary['period']->direction }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">تازگی داده</dt><dd>{{ $summary['freshness']['label'] }}</dd></div></dl>@endif</section></div>
<section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="border-b px-5 py-4"><h2 class="font-black">دفتر باکت‌ها و revisionها</h2></div><div class="overflow-x-auto"><table class="w-full text-right text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="px-4 py-3">بازه</th><th class="px-4 py-3">شناسه</th><th class="px-4 py-3">RX / TX</th><th class="px-4 py-3">وضعیت</th><th class="px-4 py-3">پردازش</th></tr></thead><tbody class="divide-y">@foreach($buckets as $bucket)<tr><td class="px-4 py-4 text-xs" dir="ltr">{{ $bucket->interval_start }}<br>{{ $bucket->interval_end }}</td><td class="px-4 py-4 font-mono text-xs" dir="ltr">{{ $bucket->bucket_id }} · r{{ $bucket->revision }}</td><td class="px-4 py-4" dir="ltr">{{ $reports->bytes($bucket->ingress_bytes) }} / {{ $reports->bytes($bucket->egress_bytes) }}</td><td class="px-4 py-4">{{ $bucket->status }} · {{ $bucket->completeness }}</td><td class="px-4 py-4">{{ $bucket->processing_status }}@if($bucket->processing_error)<p class="mt-1 text-xs text-red-600">{{ $bucket->processing_error }}</p>@endif</td></tr>@endforeach</tbody></table></div><div class="border-t px-5 py-4">{{ $buckets->links() }}</div></section></div>
@endsection
